#!/usr/python
#This is the basic console program developed in python ,
#Ultimate antiguard is a greate to tool to remove one type of purticular virus ,
#this virus is execute/spread when we double click on the 'foldername.link' file , 
#so our tool will remove the all .link folder available in the usb drive and it also delete the 'autorun files, 
#it set the folder attributes such as +H +s to all folder ,it realy makes all folder in unhide mode. 

import os
print ""
print ""
print ""
print "ULTIMATE ANTIGUARD PRO v1.0"
print "********************************"
print ""

#function to choose the drive.
def choose_drive(n):
   print "Choose the drive that you want to clean "
   print ""
   print "1 :-> C:\ "
   print "2 :-> D:\ "
   print "3 :-> E:\ "
   print "4 :-> F:\ "
   print "5 :-> G:\ "
   print ""
   print ""
   print ""
   #drive letter user input
   opt = input("option (1-5) DRIVE=> : ")
   
   if opt==1:
# change the drive address manually before executing , linux not support the drive letter such as 'C://'  linux support '/media/some drive address'
      drive="/media/" 
      scan_files(drive)
   elif opt==2:
# change the drive address manually
      drive="D:\\"
      scan_files(drive)
   elif opt==3:	 
# change the drive address manually 
      drive="E:\\"
      scan_files(drive)
   elif opt==3:	 
# change the drive address manually
      drive="F:\\"
#calling scan_files() function to retreive .link files
      scan_files(drive)
   else: 
      print "invalid entry "
      print "thanks for using ultimate antiguard pro"
      print "******************************************************"
      print ""
      print ""
#end of choose_drive()



#function to retreive the shortcut folders and the Super hidden files 
def scan_files(rtrv_drive):
   print "***************************************************** "   
   #code to list out folders and it finding out the shortcut files 
   try:
      #list out the directory available
      fileList=[os.path.normcase(f) for f in os.listdir(rtrv_drive)]
      import glob,os
      for filename in glob.glob(os.path.join(rtrv_drive,"*.lnk")):
         print filename
         #calling delete_links() for deleting filename mentioned
         delete_links(filename)
      print " Directory listing successfully completed"
   except:
      print "just check the path variable entered in the program"
   
#end of scan_files()

#function to set the attribute +s +h
def super_attribute_set(n):
   print "super_attribute_set(n)"
#end of super_attribute_set()

#function to delete the shortcut folder 'calling from inside of the scan_files()
def delete_links(delfolder):
   print "Deleting=>".delfolder
   if os.path.isfile(delfolder):
      os.remove(delfolder)
   else:
      print "File access protected by the administrator"
   
#end of delete_links()



choose_drive(5)
#scan_files(5)
#super_attribute_set(5)
#delete_links(5)



	




